FROM nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04
# USER root
# USER vscode

RUN apt-get update
RUN apt-get -y install locales && \
    localedef -f UTF-8 -i ja_JP ja_JP.UTF-8
RUN apt-get install -y vim less
RUN apt-get install wget

ENV LANG ja_JP.UTF-8
ENV LANGUAGE ja_JP:ja
ENV LC_ALL ja_JP.UTF-8
ENV TZ JST-9
ENV TERM xterm

RUN mkdir -p /root/src
COPY requirements.txt /root/src
WORKDIR /root/src

# install python3.6.15
RUN apt-get install -y git
RUN apt-get install -y build-essential libncursesw5-dev libgdbm-dev libc6-dev zlib1g-dev libsqlite3-dev tk-dev libssl-dev openssl libbz2-dev libreadline-dev
RUN mv /bin/sh /bin/sh_tmp && ln -s /bin/bash /bin/sh
RUN git clone https://github.com/yyuu/pyenv.git ~/.pyenv
RUN echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.profile &&\
    echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.profile &&\
    echo 'eval "$(pyenv init -)"' >> ~/.profile &&\
    source ~/.profile &&\
    pyenv install 3.6.15 &&\
    pyenv global 3.6.15 &&\
    pip install --upgrade pip &&\
    pip install --upgrade setuptools &&\
    pip install -r requirements.txt &&\
    python -m pip install --upgrade https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.12.0-cp36-cp36m-linux_x86_64.whl
RUN rm /bin/sh && mv /bin/sh_tmp /bin/sh

# RUN pip install --upgrade pip
# RUN pip install --upgrade setuptools
# RUN pip install -r requirements.txt

# ref: https://blauthree.hatenablog.com/entry/2019/07/13/000839
# ref: https://qiita.com/Fendo181/items/912b65c4fcc3d701d53d
# ref for tensorflow-gpu: https://stackoverflow.com/questions/55877398/how-to-install-tensorflow-version-1-12-0-with-pip
